circleci - fix for dev build

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -55,29 +55,13 @@ jobs:
             sudo docker build -t $IMAGE_NAME . || { echo "Build failed"; exit 1; }
             sudo docker inspect $IMAGE_NAME | grep -i architecture
       - run:
-          name: check image and get version
-          command: |
-            docker-compose up -d
-            echo "waiting for up ..."
-            sleep 5
-            UNIMUS_VERSION=$( docker-compose logs unimus | awk -F ':' '/version/{ print $5 }' | awk '{ print $2 }' | tail -n1 )
-            echo "Unimus version: $UNIMUS_VERSION"
-            [ -z "$UNIMUS_VERSION" ] && { echo "Unimus version not found"; exit 1; }
-            # create version tag
-            docker tag $IMAGE_NAME $IMAGE_NAME:$UNIMUS_VERSION
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:$UNIMUS_VERSION
-      - run:
           name: docker image push
           command: |
             docker images
-            docker tag $IMAGE_NAME $IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker push $IMAGE_NAME:latest || { echo "push failed"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
-            VERSION=$( docker images | grep -i $IMAGE_NAME | awk '{ print $2 }' | grep -i '^[0-9]' | sort | uniq )
-            echo "Image version: $VERSION"
-            docker push $IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
+            docker tag $IMAGE_NAME $IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
+            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
+            docker push $IMAGE_NAME:dev || { echo "push failed"; exit 1; }
+            docker push quay.io/$IMAGE_NAME:dev || { echo "push failed"; exit 1; }
   containerbuilder-arm-job:
     machine:
       image: ubuntu-2004:current
@@ -102,29 +86,13 @@ jobs:
             sudo docker build -t $IMAGE_NAME . || { echo "Build failed"; exit 1; }
             sudo docker inspect $IMAGE_NAME | grep -i architecture
       - run:
-          name: check image and get version
-          command: |
-            docker run -tid --name unimus $IMAGE_NAME || { echo "run failed"; exit 1; }
-            echo "waiting for up ..."
-            sleep 5
-            UNIMUS_VERSION=$( docker logs unimus | awk -F ':' '/version/{ print $5 }' | awk '{ print $2 }' | tail -n1 )
-            echo "Unimus version: $UNIMUS_VERSION"
-            [ -z "$UNIMUS_VERSION" ] && { echo "Unimus version not found"; exit 1; }
-            # create version tag
-            docker tag $IMAGE_NAME $IMAGE_NAME:$UNIMUS_VERSION
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:$UNIMUS_VERSION
-      - run:
           name: docker image push
           command: |
             docker images
-            docker tag $IMAGE_NAME $IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:latest || { echo "retag failed"; exit 1; }
-            docker push $IMAGE_NAME:latest || { echo "push failed"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:latest || { echo "push failed"; exit 1; }
-            VERSION=$( docker images | grep -i $IMAGE_NAME | awk '{ print $2 }' | grep -i '^[0-9]' | sort | uniq )
-            echo "Image version: $VERSION"
-            docker push $IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
-            docker push quay.io/$IMAGE_NAME:$VERSION || { echo "version ($VERSION) image push error"; exit 1; }
+            docker tag $IMAGE_NAME $IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
+            docker tag $IMAGE_NAME quay.io/$IMAGE_NAME:dev || { echo "retag failed"; exit 1; }
+            docker push $IMAGE_NAME:dev || { echo "push failed"; exit 1; }
+            docker push quay.io/$IMAGE_NAME:dev || { echo "push failed"; exit 1; }
 # workflows
 workflows:
   myflow:
